version: "3.5"
services:
  watermeter:
    image: nohn/watermeter:develop
    container_name: watermeter
    volumes:
      - ./config:/usr/src/watermeter/src/config
      - /run/shm/:/run/shm
    restart: unless-stopped
    ports:
      - "3000:3000"
