version: "3.5"
services:
  watermeter:
    build: .
    container_name: watermeter
    environment:
      - HOME_ASSISTANT_URL=http://10.20.30.20:8123
      - HOME_ASSISTANT_TOKEN=your_token
      - PICAMERA_IMAGE_PATH=/run/shm/watermeter_last.jpg
      - PICAMERA_CONFIG='{"size": (1920, 1080)}'
      - TESSERACT_PATH=/usr/bin/tesseract
      - TESSERACT_CONFIG='--psm 6 -c tessedit_char_whitelist=0123456789'
    volumes:
      - ./config:/app/config
      - /run/shm/:/run/shm
    restart: unless-stopped
    ports:
      - "3000:3000"