picamera_image_brightness: '3'
picamera_image_contrast: '1'
picamera_image_focus_manual_enabled: false
picamera_image_focus_position: '3'
picamera_image_path: /run/shm/watermeter_last.jpg
picamera_image_rotate: '270'
picamera_led_brightness: '1'
picamera_led_enabled: true
picamera_photo_height: 2000
picamera_photo_width: 2000
postgaugerois:
- [124, 1766, 167, 51]
postrois:
- [245, 207, 142, 80]
pregaugerois: []
prerois: []
tesseract_config: --psm 6 -c tessedit_char_whitelist=0123456789
tesseract_path: /usr/bin/tesseract
watermeter_init_value: 1
watermeter_job_schedule: '5'
watermeter_last_value_file: ./config/watermeter_last_value.txt
watermeter_preview_image_path: /run/shm/watermeter_preview.jpg
