picamera_debug: true
picamera_image_brightness: '0.6'
picamera_image_contrast: '3.6'
picamera_image_focus_manual_enabled: false
picamera_image_focus_position: '3'
picamera_image_path: /run/shm/watermeter_last.jpg
picamera_image_rotate: '90'
picamera_image_sharpness: '8.1'
picamera_led_brightness: '1'
picamera_led_enabled: true
picamera_photo_height: 2000
picamera_photo_width: 2000
postgaugerois:
- [1128, 1030, 153, 148]
postrois:
- [1035, 895, 34, 58]
- [1086, 892, 32, 60]
- [1130, 892, 39, 56]
pregaugerois: []
prerois:
- [835, 911, 35, 55]
- [887, 909, 33, 49]
- [934, 906, 37, 50]
- [983, 899, 39, 56]
tesseract_config: --psm 6 -c tessedit_char_whitelist=0123456789
tesseract_path: /usr/bin/tesseract
watermeter_init_value: 1
watermeter_job_schedule: '1'
watermeter_last_value_file: ./config/watermeter_last_value.txt
watermeter_preview_image_path: /run/shm/watermeter_preview.jpg
