picamera_buffer_count: '2'
picamera_debug: false
picamera_image_brightness: '0.6'
picamera_image_contrast: '2.9'
picamera_image_denoise_mode: HighQuality
picamera_image_focus_manual_enabled: false
picamera_image_focus_position: '7.4'
picamera_image_path: /run/shm/watermeter_last.jpg
picamera_image_rotate: '270'
picamera_image_sharpness: '10.2'
picamera_led_brightness: '1'
picamera_led_enabled: true
picamera_photo_height: '2500'
picamera_photo_width: '2500'
postgaugerois:
- [1667, 1234, 412, 416]
postrois:
- [1500, 870, 91, 146]
- [1629, 879, 88, 141]
- [1745, 923, 109, 135]
pregaugerois: []
prerois:
- [989, 865, 87, 137]
- [1118, 868, 81, 136]
- [1245, 869, 87, 137]
- [1373, 875, 85, 133]
watermeter_init_value: 1
watermeter_job_schedule: '5'
watermeter_last_value_file: ./config/watermeter_last_value.txt
watermeter_preview_image_path: /run/shm/watermeter_preview.jpg
