aws_profile: tikimon
aws_region: eu-central-1
aws_use_rekognition_api: true
picamera_buffer_count: '2'
picamera_debug: false
picamera_image_brightness: '0.6'
picamera_image_contrast: '3.1'
picamera_image_denoise_mode: HighQuality
picamera_image_focus_manual_enabled: false
picamera_image_focus_position: '7.4'
picamera_image_path: /run/shm/watermeter_last.jpg
picamera_image_rotate: '270'
picamera_image_sharpness: '10.2'
picamera_led_brightness: '1'
picamera_led_enabled: true
picamera_photo_height: '2500'
picamera_photo_width: '2500'
postgaugerois:
- [1700, 1235, 413, 408]
postrois:
- [1507, 851, 89, 168]
- [1632, 860, 89, 158]
- [1755, 867, 92, 192]
pregaugerois: []
prerois:
- [1002, 874, 84, 135]
- [1128, 874, 86, 132]
- [1249, 866, 88, 142]
- [1381, 876, 82, 138]
watermeter_init_value: 1
watermeter_job_schedule: '15'
watermeter_last_value_file: ./config/watermeter_last_value.txt
watermeter_preview_image_path: /run/shm/watermeter_preview.jpg
