picamera_buffer_count: '2'
picamera_debug: false
picamera_image_brightness: '0.6'
picamera_image_contrast: '2.9'
picamera_image_denoise_mode: HighQuality
picamera_image_focus_manual_enabled: false
picamera_image_focus_position: '7.4'
picamera_image_path: /run/shm/watermeter_last.jpg
picamera_image_rotate: '270'
picamera_image_sharpness: '10.2'
picamera_led_brightness: '1'
picamera_led_enabled: true
picamera_photo_height: '2500'
picamera_photo_width: '2500'
postgaugerois:
- [1700, 1235, 413, 408]
postrois:
- [1513, 863, 85, 152]
- [1634, 859, 93, 159]
- [1759, 862, 103, 195]
pregaugerois: []
prerois:
- [1016, 870, 84, 145]
- [1139, 872, 86, 136]
- [1267, 872, 87, 138]
- [1390, 870, 90, 143]
watermeter_init_value: 1
watermeter_job_schedule: '5'
watermeter_last_value_file: ./config/watermeter_last_value.txt
watermeter_preview_image_path: /run/shm/watermeter_preview.jpg
aws_use_rekognition_api: false
aws_profile: tikimon
# Check Rekognition regions: https://docs.aws.amazon.com/general/latest/gr/rekognition.html
aws_region: eu-central-1